#!/bin/bash
set -e

if [ -z "$MYSQL_REPLICATION_USER" -o -z "$MYSQL_REPLICATION_PASSWORD" ]; then
        echo >&2 "Error: No replication user specified"
        exit 1
fi

echo "
SET SQL_LOG_BIN=0;
CREATE USER '$MYSQL_REPLICATION_USER'@'%' IDENTIFIED BY '$MYSQL_REPLICATION_PASSWORD';
GRANT REPLICATION SLAVE ON *.* TO '$MYSQL_REPLICATION_USER'@'%';
FLUSH PRIVILEGES;
SET SQL_LOG_BIN=1;
RESET MASTER;
CHANGE MASTER TO MASTER_USER='$MYSQL_REPLICATION_USER', MASTER_PASSWORD='$MYSQL_REPLICATION_PASSWORD' FOR CHANNEL 'group_replication_recovery';
" | "${mysql[@]}"
